site_name: LinuxTurkey Wiki
site_url: https://linuxturkey.kavakci.dev
docs_dir: src
repo_url: https://github.com/LinuxTurkey/wiki
repo_name: LinuxTurkey/wiki
edit_uri: edit/main/src/
use_directory_urls: false
plugins: 
  - social:
      cards_layout_options:
        logo: assets/logo.png
  - search
  - offline
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  icon:
    logo: simple/linux
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune 
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  language: tr
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - index.md
  - rehberler/sss.md
  - faydali_baglantilar.md
  - Kullanıcı Rehberleri:
    - rehberler/linux_uyumlu_donanim.md
    - rehberler/lenovo_bios.md
    - rehberler/fedora-nvidia-akmod-rehberi.md
  - Editör Rehberleri:
    - rehberler/hangi_dagitim.md
    - rehberler/windowstan_linuxa.md
  - Diğer Wiki Kaynakları:
    - Nix Öğreniyoruz: https://nixogreniyoruz.kavakci.dev/

